package com.gmed.utils;

import java.util.List;
import java.util.Map;

import org.openqa.selenium.WebElement;


public class ConstantsFile {

	/**
	 * These are the variables which are present on different sheet and Different Frame names
	 */
	public static Map<String, String> loginData;
	//public static Map<String, String> medicalData;
	public static  Map<String, String> appointmentData;
	public static  Map<String, String> providerData;
	public static  Map<String, String> gPinData;
	public static final String LOGIN_VALID_USERNAME 				                   = "validUsername";
	public static final String PORTAL_VALID_USERNAME 				                   = "portalUsername";
	public static final String PORTAL_VALID_PASSWORD 				                   = "portalPassword";
	public static final String COMPLETE_USERNAME 				                       = "completeUserName";	
	public static final String PORTAL_VALID_LOCATION 				                   = "portallocation";
	public static final String PORTAL_SUBJECT_TITLE				                       = "portalsubject";
	public static final String GPIN_PAGE_TITLE                                         = "gpinpagetitle";
	public static final String INTERVIEW_FORM_NAME                                     = "inteviewformname";
	public static final String GGASTRO_PAGE_TITLE                                      = "homepagetitle";
	public static final String ACTVITY_NAME_IN_MEDICALCHART                            = "servicename";
	public static final String LOGIN_VALID_PASSWORD 				                   = "validPassword";
	public static final String ADDPROBLEMINPROFILE                                     = "addProblems";
	public static final String ADDCONDTIONSMINPROFILE                                  = "addCondtions";
	public static final String ADDIMMUNIZATIONSPROFILE                                 = "addImmunizations";
	public static final String ADDDXPROFILE                                            = "addDxStudies";
	public static final String ADDPRECEDUREPROFILE                                     = "addProcedures";
	public static final String ADD_ALLERGIES_INPROFILE                                 = "addAllergies";
	public static final String VALID_PATIENT_MAILID                                    = "mailId";
	public static final String PORTAL_LOGIN_VALID_PASSWORD 				               = "portalpassword";
	public static final String USER_FIRST_NAME                                         = "firstname";
	public static final String USER_FIRST_NAME_VALUE                                   = "j";
	public static final String USER_LAST_NAME                                          = "lastname";
	public static final String USER_ROLE                                               = "role";
	public static final String USER_NAME                                               = "username";
	public static final String PASSWORD                                                = "password";
	public static final String CONFIRMATION                                            = "confirmation";
	public static final String LOCATION                                                =  "location";
	public static final String PROVIDER_FIRST_NAME                                     = "providerfirstname";
	public static final String PROVIDER_LAST_NAME                                      = "providerlastname";
	public static final String REFERRING_PHYSICIAN                                     = "refferringphysicianname";
	public static final String APPOINTMENT_Row                                         = "appointmentrowvalue";
	public static final String LOGIN_VALID_NEWUSERNAME                                 = "validnewuser";
	public static final String APPOINTMENT_LOCATION                                    =  "locationname";
	public static final String APPOINTMENT_POPUPVALUE                                  =  "popupvalue";
	public static final String APPOINTMENT_ACTIVITY                                    =  "patientactivity";
	public static final String APPOINTMENT_PROVIDER                                    = "provider";
	public static final String APPOINTMENT_PROVIDER1                                   = "provider1";
	public static final String APPOINTMENT_REFFERRING_PHYSICIANS                       = "referringphysician";
	public static final String BREAK_THE_GLASS_USER1                                   =  "username1";
	public static final String BREAK_THE_GLASS_PASSWORD1                               =  "userpassword";
	public static final String BREAK_THE_GLASS_USER2                                   =  "username2";
	public static boolean isYesNo = false;
	public static boolean isOkayPresent = false;
	public static boolean isYesNoApp=false;
	public static boolean isDropDown=false;
	public static boolean isAppointmentSection=false;
	public static String appointmentStatus="Scheduled";
	public static String userfirstname;
	public static String newFileNamePathForException=null;
	public static String breakTheGlassuser1="user1";
	public static String mainUser="automation";
	public static String breakTheGlasspassword="12";
	public static String breakTheGlassuser2="user2";
	public static String ColonIntialname = "Colonoscopy";
	public static String ColonIntialTemplatename = "Colon";
	public static boolean diagnosisIsPopulated = false;
	public static boolean procedurecodeIsPopulated = false;
	public static boolean serviceIsPopulated=false;
	public static boolean billingproviderIsPopulated=false;
	public static String FirstVisitIntialTemplatename = "FirstVisit";
	public static String FirstVisitIntialname = "First_visit";
	public static String billingnotes = "test billing alerts";
	public static String interviewformname;
	public static String userfirstnamerandomno;
	public static String userfirstnamevalues;
	public static String userlastname;
	public static String userlastnamerandomno;
	public static String userlastnamevalues;
	public static String partialusername;
	public static String username;
	public static String password;
	public static Boolean isPatientCreated=false;
	public static String usernamedata;
	public static String usernamerandomno;
	public static String usernamevalues;
	public static String usercompletelastname;
	public static String providerfirstnamerandomno;
	public static String providerfirstname;
	public static String providerfirstnamevalues;
	public static String providercompletelastname;
	public static String providerlastname;
	public static String providerlastnamerandomno;
	public static String providerlastnamevalues;
	public static String patientIntialname = "Tomcat";
	public static String diagnosticIntialname = "colonscopy";
	public static String TaskIntialName;
	public static String orderIntialName;
	public static String locationname = "Automation";
	public static String Fulllocationname = "Automation";
	public static String patientfirstname;
	public static String patientlastname;
	public static String passwordvalue;
	public static String usernamevalue;
	public static String sysadminrole;
	public static String MRN;
	public static String SSN0;
	public static String SSN1;
	public static String SSN2;
	public static String mobile00;
	public static String mobile01;
	public static String mobile02;
	public static String MRNWithoutIns;
	public static String accountNumber;
	public static boolean popupvalue=false;
	public static boolean isUserAssociated=false;
	public static boolean isPatientChartPresent=false;
	public static String userlistpanelTitle;
	public static boolean userlistpanelexist=false;
	public static boolean medicationdatapopulated=false;
	public static boolean allergiesisdocumented=false;
	public static boolean condtionisdocumented=false;
	public static boolean immunizationsdocumented=false;
	public static boolean dxStudiesdocumented=false;
	public static boolean procedureisdocumented=false;
	public static boolean isFolderisExpanded=false;
	public static boolean isproblemisDocumented=false;
	public static boolean isschdulerisOpened=false;
	public static boolean isPatientisSearched=false;
	public static boolean autopopulatedFielsInAppointment=false;
	public static boolean patientscreenInAppointment=false;
	public static boolean ispatientNamePopulatedInAppointment=false;
	public static boolean isproviderNamePopulatedInAppointment=false;
	public static boolean requiredFieldValidationInAppointment=false;
	public static boolean isPanelListisOpened=false;
	public static boolean isTestPass=true;
	public static String buUnit ="BU Main";
	public static boolean isLoggedIn=false;
	public static boolean isNewLoggedIn=false;
	public static boolean prescriptionPopup=false;
	public static boolean prescriptionExistingPopup=false;
	public static boolean ismedicationDocumented=false;
	public static boolean rightuserlist=false;
	public static boolean conditionuserlist=false;
	public static boolean immunizationuserlist=false;
	public static boolean dxstudiesuserlist=false;
	public static boolean procedureuserlist=false;
	public static boolean switchframevarible=false;
	public static boolean Isselectinterventionvaluepopulated=false;
	public static String newFileNamePath=null;
	public static List<WebElement> rolesvalue;
	public static String patientfirstnamewithoutIns;
	public static String patientlastnamewithoutIns;
	public static String portalusername;
	public static String portalpassword;
	public static String recallDate;
	public static String recallMonthValue;
	public static String recalldayValue;
	public static String recallYearValue;
	public static String mipsReportName;
	public static String portalUser;
	public static String portalpasswordDetails;
	
	public static GenerateData genData = new GenerateData();
	public static GenerateData genData1 = new GenerateData();
	//---
	public static String patientchartpatientname = "Test AgainIn";
	public static String patientchartfirstname = "Test";
	public static String usernamevalue1 = "bhuwan";
	public static String passwordvalue1 = "12";
	public static String charttitle;
	public static String mailsubject;
	public static String chartname;
	public static String TaskIntialMessageName;
	public static String loginUserName;
	public static String anotherLoginUserName;
	public static String messageIntialName;
	public static String directmessageIntialName;
	public static String doseDetails;
	public static String providerValue;
	public static String pharmacyValue;
	public static String completeUserName;
	public static String medicationName;
	public static String deleteMedicationName;
}
